library(shiny)
 
 
 
 
# Define UI for dataset viewer application
shinyUI(pageWithSidebar(
 
  # Application title
  headerPanel("Protracted birth death"),
 
  # Sidebar with controls to select a dataset and specify the number
  # of observations to view
  sidebarPanel(
	sliderInput("goodrate", 
                "speciation rate of good species:", 
                min = 0.00,
                max = 1.0, 
                value = 0.4,step=0.01,ticks=T),
	sliderInput("compprate", 
                "speciation completion rate:", 
                min = 0.00,
                max = 1.0, 
                value = 1.0,step=0.01,ticks=T),
	sliderInput("inciprate", 
                "speciation rate of incipient species:", 
                min = 0.0,
                max = 1.0, 
                value = 0.4,step=0.01,ticks=T),
	sliderInput("extgood", 
                "extinction rate of good species:", 
                min = 0.0,
                max = 1.0, 
                value = 1.0,step=0.01,ticks=T),
	sliderInput("extincip", 
                "extinction rate of incipient species:", 
                min = 0.0,
                max = 1.0, 
                value = 1.0,step=0.01,ticks=T),			
    sliderInput("goodrate2", 
                "2nd speciation rate of good species:", 
                min = 0.0,
                 max = 1.0, 
                value = 0.4,step=0.01,ticks=T),
	sliderInput("compprate2", 
                "2nd speciation completion rate:", 
                min = 0.0,
                max = 1.0, 
                value = 1.0,step=0.01,ticks=T),
	sliderInput("inciprate2", 
                "2nd speciation rate of incipient species:", 
                min = 0.0,
                 max = 1.0, 
                value = 0.4,step=0.01,ticks=T),
	sliderInput("extgood2", 
                "2nd extinction rate of good species:", 
                min = 0.0,
                max = 1.0, 
                value = 1.0,step=0.01,ticks=T),
	sliderInput("extincip2", 
                "2nd extinction rate of incipient species:", 
                min = 0.0,
                max = 1.0, 
                value = 1.0,step=0.01,ticks=T),
	selectInput("variable", "Choose a variable:", 
                choices = c("meanlivingsp", "meanlivingin",  "meanextsp", "meanextin"  ,"meantaxa", "sdlivingsp", "sdlivingin" ,  "sdextsp",   "sdextin"  ,  "sdtaxa","cvlivingsp","cvlivingin",  "cvextsp", "cvextin"  ,"cvtaxa"))
  ),
mainPanel(
    tabsetPanel(
      tabPanel("Species plots", plotOutput("Plot1"),plotOutput("Plot2")),
	  tabPanel("On the fly", plotOutput("Plot3"),plotOutput("Plot4")),
	  tabPanel("by variable",plotOutput("Plot5"),plotOutput("Plot6"),plotOutput("Plot7"),plotOutput("Plot8"),plotOutput("Plot9")),
	  tabPanel("phylograms",plotOutput("Plot12"),plotOutput("Plot13")),
	  tabPanel("contourplots",
		selectInput("variable1", "Choose an output to plot:", 
                choices = c("meanlivingsp","meanlivingin","meanextsp","meanextin","meantaxa","sdlivingsp","sdlivingin","sdextsp","sdextin","sdtaxa","cvlivingsp","cvlivingin","cvextsp","cvextin","cvtaxa")),
		checkboxInput("lograte1", "logged?", value = FALSE),
		sliderInput("binrate1","numberofbins",min=0,max=200,value=10,step=1,ticks=T),
		selectInput("plotx", "Choose a variable to be x axis: a is goodrate,b is completionrate, d is inciprate, e is goodextinct, f is incipextinct",choices = c("a","b","d","e","f"),selected="a"),
		selectInput("ploty", "Choose a variable to be y axis:",choices = c("a","b","d","e","f"),selected="b"),
		selectInput("fixed1", "Choose first variable to be fixed:",choices = c("a","b","d","e","f"),selected="d"),
		sliderInput("fixed1rate", 
                "rate", 
                min = 0.0,
                 max = 1.0, 
                value = 0.4,step=0.01,ticks=T),
		selectInput("fixed2", "Choose second variable to be fixed:",choices = c("a","b","d","e","f"),selected="e"),
		sliderInput("fixed2rate", 
                "rate", 
                min = 0.0,
                 max = 1.0, 
                value = 0.4,step=0.01,ticks=T),
		selectInput("fixed3", "Choose last variable to be fixed:",choices = c("a","b","d","e","f"),selected="f"),
		sliderInput("fixed3rate", 
                "rate", 
                min = 0.0,
                 max = 1.0, 
                value = 0.4,step=0.01,ticks=T),
		plotOutput("Plot10"),
		selectInput("variable2", "Choose an output to plot:", 
                choices = c("meanlivingsp","meanlivingin","meanextsp","meanextin","meantaxa","sdlivingsp","sdlivingin","sdextsp","sdextin","sdtaxa","cvlivingsp","cvlivingin","cvextsp","cvextin","cvtaxa")),
		checkboxInput("lograte2", "logged?", value = FALSE),
		sliderInput("binrate2","numberofbins",min=0,max=200,value=10,step=1,ticks=T),
		selectInput("plotx2", "Choose a variable to be x axis for second plot:",choices = c("a","b","d","e","f"),selected="a"),
		selectInput("ploty2", "Choose a variable to be y axis for second plot:",choices = c("a","b","d","e","f"),selected="b"),
		selectInput("fixed12", "Choose first variable to be fixed:",choices = c("a","b","d","e","f"),selected="d"),
		sliderInput("fixed1rate2", 
                "rate", 
                min = 0.0,
                 max = 1.0, 
                value = 0.4,step=0.01,ticks=T),
		selectInput("fixed22", "Choose second variable to be fixed:",choices = c("a","b","d","e","f"),selected="e"),
		sliderInput("fixed2rate2", 
                "rate", 
                min = 0.0,
                 max = 1.0, 
                value = 0.4,step=0.01,ticks=T),
		selectInput("fixed32", "Choose last variable to be fixed:",choices = c("a","b","d","e","f"),selected="f"),
		sliderInput("fixed3rate2", 
                "rate", 
                min = 0.0,
                 max = 1.0, 
                value = 0.4,step=0.01,ticks=T),
		plotOutput("Plot11")
      ),
	  tabPanel("tau",
	  selectInput("tauvariable", "Choose a variable to fix:", 
                choices = c("speccomp","incipsp","incipext")),
	  sliderInput("taurate", 
                "value", 
                min = 0.0,
                 max = 1.0, 
                value = 0.4,step=0.01,ticks=T),
          sliderInput("maxcolour","max colour",min=0.0,max=100.0,value=8,step=0.01,ticks=T),
	  plotOutput("Plot14")
	  )
  ))
))